USE employees_db;

INSERT INTO department (name)
VALUES ("Sales")
INSERT INTO department (name)
VALUES ("Office Administration")
INSERT INTO department (name)
VALUES ("Accounting")
INSERT INTO department (name)
VALUES ("Marketing")

INSERT INTO role (title, salary, department_id)
VALUES ("Dir. of Bus. Ops", 100000, 2)
INSERT INTO role (title, salary, department_id)
VALUES ("Social Media Guru", 70000, 4)
INSERT INTO role (title, salary, department_id)
VALUES ("CPA", 85000, 3)
INSERT INTO role (title, salary, department_id)
VALUES ("Office Mgr", 57500, 2)
INSERT INTO role (title, salary, department_id)
VALUES ("Marketing Dir", 78250, 4)
INSERT INTO role (title, salary, department_id)
VALUES ("Sales Mgr", 125000, 1)

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ("Shawn", "Smith", 1, NULL)
INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ("Syrah", "Kine", 5, NULL)
INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ("Bill", "Schmelber", 4, 1)
INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ("Jean", "Morgan", 3, NULL)
INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ("Corey", "Mushy", 2, 2)
INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ("Wilma", "Barnett", 6, NULL)